services:
  giant-component-networks:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    build:
      context: .
    container_name: giant-component-networks
    environment:
      - TRACKER_API=https://skillab-tracker.csd.auth.gr/api
      - KU_API_URL=https://se.uom.gr/skillab-public-ku-detection
    ports:
      - '8003:8000'
    labels:
      io.portainer.accesscontrol.teams: skillab-all